#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postrm.d && run-parts --arg="3.19.0-armv7-1" --arg="/boot/vmlinuz-3.19.0-armv7-1" /etc/kernel/postrm.d
exit 0
